version: "3.7"
services:
  proxy:
    image: wicksome/haproxy-example:latest
    build:
      context: .
    ports:
      - 90:80
      - 8080:8080
    networks:
      - devops
networks:
  devops:
    external:
      name: devops